import json
import os

class VoodooGenerator:
    def __init__(self, template_dir="voodoo_architect/templates"):
        self.template_dir = template_dir
        if not os.path.exists(self.template_dir):
            os.makedirs(self.template_dir)
            self._create_default_template()

    def _create_default_template(self):
        template_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <meta name="description" content="{{description}}">
    <style>
        body { font-family: 'Inter', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 2rem; }
        header { border-bottom: 2px solid #eee; margin-bottom: 2rem; padding-bottom: 1rem; }
        h1 { color: #2c3e50; }
        .content { margin-bottom: 2rem; }
        footer { margin-top: 3rem; font-size: 0.8rem; color: #777; text-align: center; }
        .link-list { list-style: none; padding: 0; }
        .link-list li { margin: 0.5rem 0; }
    </style>
</head>
<body>
    <header>
        <h1>{{title}}</h1>
        <p><em>{{description}}</em></p>
    </header>
    <div class="content">
        {{content}}
    </div>
    <footer>
        <p>Generated by Voodoo Architect AI</p>
    </footer>
</body>
</html>
"""
        with open(os.path.join(self.template_dir, "default.html"), "w") as f:
            f.write(template_content)

    def generate_html(self, scraped_data, output_path="index.html"):
        print(f"Generating website from scraped data...")
        
        # Ensure template exists before loading
        if not os.path.exists(os.path.join(self.template_dir, "default.html")):
            self._create_default_template()

        # Load template
        with open(os.path.join(self.template_dir, "default.html"), "r") as f:
            template = f.read()

        # Basic template filling
        html = template.replace("{{title}}", scraped_data.get('title', 'New Website'))
        html = html.replace("{{description}}", scraped_data.get('meta_description', ''))
        
        # Format content from headings and text
        content_html = ""
        for h in scraped_data.get('headings', []):
            content_html += f"<{h['tag']}>{h['text']}</{h['tag']}>\n"
        
        # In a real scenario, we would use a more sophisticated LLM to rewrite the content
        # For this implementation, we'll use the extracted content text
        content_html += f"<p>{scraped_data.get('content', '')[:2000]}...</p>"
        
        html = html.replace("{{content}}", content_html)

        with open(output_path, "w") as f:
            f.write(html)
        
        return output_path

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 2:
        # Expecting: python generator.py 'json_data' output_file
        data = json.loads(sys.argv[1])
        gen = VoodooGenerator()
        result = gen.generate_html(data, sys.argv[2])
        print(f"Website generated at: {result}")
    else:
        print("Usage: python generator.py '<json_data>' <output_file>")
